name: Build and Deploy Docker Image to GCR

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:   
    - name: Configure Docker
      run: |
       docker login --username=mugumbyabenon --password=@Kibuuka1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        #file: ./MakWebSystem/Dockerfile
        push: true
        tags: gcr.io/makereremanifest/mak-web-system:latest
